- name: loops
  hosts: localhost
  tasks:
  - name: Install and Print the Packgs
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - postfix
  