- name: variables from play level
  hosts: localhost
  vars:
    course: "DevOps"
    trainer: "SKR"
    duration: "110hrs"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"
